### ISSUE TITLE
 Exception in thread "AWT-EventQueue-0" java.awt.IllegalComponentStateException: The frame is decorated

### ISSUE THREAD

**Issue by computersarecool** [onformative/ScreenCapturer#2]
When trying to run the example I get the following:

```
Exception in thread "AWT-EventQueue-0" java.awt.IllegalComponentStateException: The frame is decorated
    at java.awt.Frame.setBackground(Frame.java:986)
    at com.onformative.screencapturer.Screen$2.run(Screen.java:115)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:251)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
ScreenCapturer: Width: 600 Height: 600 Proportion: 1.0
```

And the sketch does not work. Only a gray screen appears.

**Comment by clankill3r** [comment]
I have the same problem as well.
I want to fix the library tomorrow.

**Comment by muestra** [comment]
Any help with this problem? I have it too!
thanks

**Comment by clankill3r** [comment]
I looked into it but there where more things not done really well. 

You can run this without needing the library:

SimpleScreenCapture simpleScreenCapture;

void setup() {
  size(600, 400);
  simpleScreenCapture = new SimpleScreenCapture();

}

void draw() {

  image(simpleScreenCapture.get(), 0, 0, width, height);

}

---

import java.awt.Robot;
import java.awt.Rectangle;
import java.awt.AWTException;

class SimpleScreenCapture {

  Robot robot;

  PImage screenshot;

  SimpleScreenCapture() {
    try {
      robot = new Robot();
    }
    catch (AWTException e) {
      println(e);
    }
  }

  PImage get() {
    screenshot = new PImage(robot.createScreenCapture(new Rectangle(0, 0, width, height)));
    return screenshot;
  }

}

**Comment by i-make-robots** [comment]
I can confirm this alternate method works.  Can you suggest how to make the screen capture region moveable/sizeable?  I'd really like those features.

**Comment by clankill3r** [comment]
That will be some more work. I suggest to look into the onformative/ScreenCapturer source code for that.

**Comment by joernroeder** [comment]
@clankill3r thanks for sharing this quick solution! :+1:
